{
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "!git clone https://github.com/shu4dev/ECE491_Assignment2.git\n",
        "%cd ECE491_Assignment2\n",
        "!git pull\n",
        "!git checkout main\n",
        "!pip install -e ./cs336-basics/ -e ./cs336-data/'[test]'"
      ],
      "metadata": {
        "id": "1xXvV-7XUqZv",
        "outputId": "56432af2-fd1c-490c-b4da-091617f2e26b",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "fatal: destination path 'ECE491_Assignment2' already exists and is not an empty directory.\n",
            "/content/ECE491_Assignment2\n",
            "Already up to date.\n",
            "Already on 'main'\n",
            "Your branch is up to date with 'origin/main'.\n",
            "Obtaining file:///content/ECE491_Assignment2/cs336-basics\n",
            "  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Obtaining file:///content/ECE491_Assignment2/cs336-data\n",
            "  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (from cs336_basics==0.0.0.dev0) (2024.11.6)\n",
            "Collecting torch==2.2.1 (from cs336_basics==0.0.0.dev0)\n",
            "  Downloading torch-2.2.1-cp311-cp311-manylinux1_x86_64.whl.metadata (26 kB)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from cs336_basics==0.0.0.dev0) (2.0.2)\n",
            "Requirement already satisfied: wandb in /usr/local/lib/python3.11/dist-packages (from cs336_basics==0.0.0.dev0) (0.19.8)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch==2.2.1->cs336_basics==0.0.0.dev0) (3.18.0)\n",
            "Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.2.1->cs336_basics==0.0.0.dev0) (4.12.2)\n",
            "Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from torch==2.2.1->cs336_basics==0.0.0.dev0) (1.13.1)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch==2.2.1->cs336_basics==0.0.0.dev0) (3.4.2)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch==2.2.1->cs336_basics==0.0.0.dev0) (3.1.6)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch==2.2.1->cs336_basics==0.0.0.dev0) (2025.3.0)\n",
            "Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)\n",
            "Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)\n",
            "Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)\n",
            "Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)\n",
            "Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)\n",
            "Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)\n",
            "Collecting triton==2.2.0 (from torch==2.2.1->cs336_basics==0.0.0.dev0)\n",
            "  Downloading triton-2.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)\n",
            "Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.1->cs336_basics==0.0.0.dev0) (12.5.82)\n",
            "Collecting xopen (from cs336_data==0.0.4)\n",
            "  Downloading xopen-2.0.2-py3-none-any.whl.metadata (15 kB)\n",
            "Collecting resiliparse (from cs336_data==0.0.4)\n",
            "  Downloading resiliparse-0.15.2-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.7 kB)\n",
            "Collecting fasttext (from cs336_data==0.0.4)\n",
            "  Downloading fasttext-0.9.3.tar.gz (73 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m73.4/73.4 kB\u001b[0m \u001b[31m4.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Installing build dependencies ... \u001b[?25l\u001b[?25hdone\n",
            "  Getting requirements to build wheel ... \u001b[?25l\u001b[?25hdone\n",
            "  Preparing metadata (pyproject.toml) ... \u001b[?25l\u001b[?25hdone\n",
            "Requirement already satisfied: pytest in /usr/local/lib/python3.11/dist-packages (from cs336_data==0.0.4) (8.3.5)\n",
            "Collecting pybind11>=2.2 (from fasttext->cs336_data==0.0.4)\n",
            "  Using cached pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)\n",
            "Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from fasttext->cs336_data==0.0.4) (75.1.0)\n",
            "Requirement already satisfied: iniconfig in /usr/local/lib/python3.11/dist-packages (from pytest->cs336_data==0.0.4) (2.1.0)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from pytest->cs336_data==0.0.4) (24.2)\n",
            "Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.11/dist-packages (from pytest->cs336_data==0.0.4) (1.5.0)\n",
            "Collecting fastwarc==0.15.2 (from resiliparse->cs336_data==0.0.4)\n",
            "  Downloading fastwarc-0.15.2-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.2 kB)\n",
            "Collecting brotli (from fastwarc==0.15.2->resiliparse->cs336_data==0.0.4)\n",
            "  Downloading Brotli-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)\n",
            "Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from fastwarc==0.15.2->resiliparse->cs336_data==0.0.4) (8.1.8)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from fastwarc==0.15.2->resiliparse->cs336_data==0.0.4) (4.67.1)\n",
            "Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (0.4.0)\n",
            "Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (3.1.44)\n",
            "Requirement already satisfied: platformdirs in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (4.3.7)\n",
            "Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (5.29.4)\n",
            "Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (5.9.5)\n",
            "Requirement already satisfied: pydantic<3,>=2.6 in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (2.10.6)\n",
            "Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (6.0.2)\n",
            "Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (2.32.3)\n",
            "Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (2.24.0)\n",
            "Requirement already satisfied: setproctitle in /usr/local/lib/python3.11/dist-packages (from wandb->cs336_basics==0.0.0.dev0) (1.3.5)\n",
            "Collecting isal>=1.6.1 (from xopen->cs336_data==0.0.4)\n",
            "  Downloading isal-1.7.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)\n",
            "Collecting zlib-ng>=0.4.1 (from xopen->cs336_data==0.0.4)\n",
            "  Downloading zlib_ng-0.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)\n",
            "Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from docker-pycreds>=0.4.0->wandb->cs336_basics==0.0.0.dev0) (1.17.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb->cs336_basics==0.0.0.dev0) (4.0.12)\n",
            "Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=2.6->wandb->cs336_basics==0.0.0.dev0) (0.7.0)\n",
            "Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=2.6->wandb->cs336_basics==0.0.0.dev0) (2.27.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.0.0->wandb->cs336_basics==0.0.0.dev0) (3.4.1)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.0.0->wandb->cs336_basics==0.0.0.dev0) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.0.0->wandb->cs336_basics==0.0.0.dev0) (2.3.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.0.0->wandb->cs336_basics==0.0.0.dev0) (2025.1.31)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch==2.2.1->cs336_basics==0.0.0.dev0) (3.0.2)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->torch==2.2.1->cs336_basics==0.0.0.dev0) (1.3.0)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb->cs336_basics==0.0.0.dev0) (5.0.2)\n",
            "Downloading torch-2.2.1-cp311-cp311-manylinux1_x86_64.whl (755.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m755.6/755.6 MB\u001b[0m \u001b[31m1.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m410.6/410.6 MB\u001b[0m \u001b[31m4.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m14.1/14.1 MB\u001b[0m \u001b[31m57.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m23.7/23.7 MB\u001b[0m \u001b[31m36.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m823.6/823.6 kB\u001b[0m \u001b[31m34.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m731.7/731.7 MB\u001b[0m \u001b[31m2.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m121.6/121.6 MB\u001b[0m \u001b[31m7.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m56.5/56.5 MB\u001b[0m \u001b[31m10.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m124.2/124.2 MB\u001b[0m \u001b[31m8.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m196.0/196.0 MB\u001b[0m \u001b[31m6.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m166.0/166.0 MB\u001b[0m \u001b[31m6.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m99.1/99.1 kB\u001b[0m \u001b[31m7.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading triton-2.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m167.9/167.9 MB\u001b[0m \u001b[31m6.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading resiliparse-0.15.2-cp311-cp311-manylinux_2_28_x86_64.whl (5.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.6/5.6 MB\u001b[0m \u001b[31m57.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading fastwarc-0.15.2-cp311-cp311-manylinux_2_28_x86_64.whl (2.4 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.4/2.4 MB\u001b[0m \u001b[31m54.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading xopen-2.0.2-py3-none-any.whl (17 kB)\n",
            "Downloading isal-1.7.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (260 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m260.8/260.8 kB\u001b[0m \u001b[31m19.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hUsing cached pybind11-2.13.6-py3-none-any.whl (243 kB)\n",
            "Downloading zlib_ng-0.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (108 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m108.2/108.2 kB\u001b[0m \u001b[31m7.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading Brotli-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.9/2.9 MB\u001b[0m \u001b[31m54.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hBuilding wheels for collected packages: fasttext\n",
            "  Building wheel for fasttext (pyproject.toml) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for fasttext: filename=fasttext-0.9.3-cp311-cp311-linux_x86_64.whl size=4313507 sha256=e5088e12de5a3819dcbbd4f39464fdc015e80fc2a5703da36c6e0c6a9830d9c5\n",
            "  Stored in directory: /root/.cache/pip/wheels/65/4f/35/5057db0249224e9ab55a513fa6b79451473ceb7713017823c3\n",
            "Successfully built fasttext\n",
            "Installing collected packages: brotli, zlib-ng, triton, pybind11, nvidia-nvtx-cu12, nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, isal, fastwarc, xopen, resiliparse, nvidia-cusolver-cu12, nvidia-cudnn-cu12, fasttext, torch, cs336_data, cs336_basics\n",
            "  Attempting uninstall: triton\n",
            "    Found existing installation: triton 3.2.0\n",
            "    Uninstalling triton-3.2.0:\n",
            "      Successfully uninstalled triton-3.2.0\n",
            "  Attempting uninstall: nvidia-nvtx-cu12\n",
            "    Found existing installation: nvidia-nvtx-cu12 12.4.127\n",
            "    Uninstalling nvidia-nvtx-cu12-12.4.127:\n",
            "      Successfully uninstalled nvidia-nvtx-cu12-12.4.127\n",
            "  Attempting uninstall: nvidia-nccl-cu12\n",
            "    Found existing installation: nvidia-nccl-cu12 2.21.5\n",
            "    Uninstalling nvidia-nccl-cu12-2.21.5:\n",
            "      Successfully uninstalled nvidia-nccl-cu12-2.21.5\n",
            "  Attempting uninstall: nvidia-cusparse-cu12\n",
            "    Found existing installation: nvidia-cusparse-cu12 12.5.1.3\n",
            "    Uninstalling nvidia-cusparse-cu12-12.5.1.3:\n",
            "      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3\n",
            "  Attempting uninstall: nvidia-curand-cu12\n",
            "    Found existing installation: nvidia-curand-cu12 10.3.6.82\n",
            "    Uninstalling nvidia-curand-cu12-10.3.6.82:\n",
            "      Successfully uninstalled nvidia-curand-cu12-10.3.6.82\n",
            "  Attempting uninstall: nvidia-cufft-cu12\n",
            "    Found existing installation: nvidia-cufft-cu12 11.2.3.61\n",
            "    Uninstalling nvidia-cufft-cu12-11.2.3.61:\n",
            "      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61\n",
            "  Attempting uninstall: nvidia-cuda-runtime-cu12\n",
            "    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82\n",
            "    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:\n",
            "      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82\n",
            "  Attempting uninstall: nvidia-cuda-nvrtc-cu12\n",
            "    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82\n",
            "    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:\n",
            "      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82\n",
            "  Attempting uninstall: nvidia-cuda-cupti-cu12\n",
            "    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82\n",
            "    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:\n",
            "      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82\n",
            "  Attempting uninstall: nvidia-cublas-cu12\n",
            "    Found existing installation: nvidia-cublas-cu12 12.5.3.2\n",
            "    Uninstalling nvidia-cublas-cu12-12.5.3.2:\n",
            "      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2\n",
            "  Attempting uninstall: nvidia-cusolver-cu12\n",
            "    Found existing installation: nvidia-cusolver-cu12 11.6.3.83\n",
            "    Uninstalling nvidia-cusolver-cu12-11.6.3.83:\n",
            "      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83\n",
            "  Attempting uninstall: nvidia-cudnn-cu12\n",
            "    Found existing installation: nvidia-cudnn-cu12 9.3.0.75\n",
            "    Uninstalling nvidia-cudnn-cu12-9.3.0.75:\n",
            "      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75\n",
            "  Attempting uninstall: torch\n",
            "    Found existing installation: torch 2.6.0+cu124\n",
            "    Uninstalling torch-2.6.0+cu124:\n",
            "      Successfully uninstalled torch-2.6.0+cu124\n",
            "  Running setup.py develop for cs336_data\n",
            "  Running setup.py develop for cs336_basics\n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "torchvision 0.21.0+cu124 requires torch==2.6.0, but you have torch 2.2.1 which is incompatible.\n",
            "torchaudio 2.6.0+cu124 requires torch==2.6.0, but you have torch 2.2.1 which is incompatible.\u001b[0m\u001b[31m\n",
            "\u001b[0mSuccessfully installed brotli-1.1.0 cs336_basics-0.0.0.dev0 cs336_data-0.0.4 fasttext-0.9.3 fastwarc-0.15.2 isal-1.7.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvtx-cu12-12.1.105 pybind11-2.13.6 resiliparse-0.15.2 torch-2.2.1 triton-2.2.0 xopen-2.0.2 zlib-ng-0.5.1\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pytest -v"
      ],
      "metadata": {
        "id": "wEg7OIBfWDD7",
        "outputId": "fb80377b-2366-42bf-c21b-dee3371ac9f6",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[1m======================================= test session starts ========================================\u001b[0m\n",
            "platform linux -- Python 3.11.11, pytest-8.3.5, pluggy-1.5.0 -- /usr/bin/python3\n",
            "cachedir: .pytest_cache\n",
            "rootdir: /content/ECE491_Assignment2\n",
            "plugins: langsmith-0.3.18, anyio-4.9.0, typeguard-4.4.2\n",
            "collected 0 items / 6 errors                                                                       \u001b[0m\n",
            "\n",
            "============================================== ERRORS ==============================================\n",
            "\u001b[31m\u001b[1m_____________________ ERROR collecting cs336-data/tests/test_deduplication.py ______________________\u001b[0m\n",
            "\u001b[31mImportError while importing test module '/content/ECE491_Assignment2/cs336-data/tests/test_deduplication.py'.\n",
            "Hint: make sure your test modules/packages have valid Python names.\n",
            "Traceback:\n",
            "/usr/lib/python3.11/importlib/__init__.py:126: in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "cs336-data/tests/test_deduplication.py:6: in <module>\n",
            "    from .adapters import run_exact_line_deduplication, run_minhash_deduplication\n",
            "cs336-data/tests/adapters.py:10: in <module>\n",
            "    from cs336_data.minhash_deduplication import fuzzy_deduplication\n",
            "cs336-data/cs336_data/minhash_deduplication.py:2: in <module>\n",
            "    import mmh3\n",
            "E   ModuleNotFoundError: No module named 'mmh3'\u001b[0m\n",
            "----------------------------------------- Captured stderr ------------------------------------------\n",
            "\n",
            "A module that was compiled using NumPy 1.x cannot be run in\n",
            "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
            "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
            "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
            "\n",
            "If you are a user of the module, the easiest solution will be to\n",
            "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
            "We expect that some modules will need time to support NumPy 2.\n",
            "\n",
            "Traceback (most recent call last):  File \"/usr/local/bin/pytest\", line 10, in <module>\n",
            "    sys.exit(console_main())\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/config/__init__.py\", line 201, in console_main\n",
            "    code = main()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/config/__init__.py\", line 175, in main\n",
            "    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/pluggy/_hooks.py\", line 513, in __call__\n",
            "    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/pluggy/_manager.py\", line 120, in _hookexec\n",
            "    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/pluggy/_callers.py\", line 103, in _multicall\n",
            "    res = hook_impl.function(*args)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 330, in pytest_cmdline_main\n",
            "    return wrap_session(config, _main)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 283, in wrap_session\n",
            "    session.exitstatus = doit(config, session) or 0\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 336, in _main\n",
            "    config.hook.pytest_collection(session=session)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/pluggy/_hooks.py\", line 513, in __call__\n",
            "    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/pluggy/_manager.py\", line 120, in _hookexec\n",
            "    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/pluggy/_callers.py\", line 103, in _multicall\n",
            "    res = hook_impl.function(*args)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 347, in pytest_collection\n",
            "    session.perform_collect()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 809, in perform_collect\n",
            "    self.items.extend(self.genitems(node))\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 975, in genitems\n",
            "    yield from self.genitems(subnode)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 975, in genitems\n",
            "    yield from self.genitems(subnode)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 975, in genitems\n",
            "    yield from self.genitems(subnode)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 970, in genitems\n",
            "    rep, duplicate = self._collect_one_node(node, handle_dupes)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/main.py\", line 835, in _collect_one_node\n",
            "    rep = collect_one_node(node)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/runner.py\", line 567, in collect_one_node\n",
            "    rep: CollectReport = ihook.pytest_make_collect_report(collector=collector)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/pluggy/_hooks.py\", line 513, in __call__\n",
            "    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/pluggy/_manager.py\", line 120, in _hookexec\n",
            "    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/pluggy/_callers.py\", line 103, in _multicall\n",
            "    res = hook_impl.function(*args)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/runner.py\", line 391, in pytest_make_collect_report\n",
            "    call = CallInfo.from_call(\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/runner.py\", line 341, in from_call\n",
            "    result: TResult | None = func()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/runner.py\", line 389, in collect\n",
            "    return list(collector.collect())\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/python.py\", line 549, in collect\n",
            "    self._register_setup_module_fixture()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/python.py\", line 562, in _register_setup_module_fixture\n",
            "    self.obj, (\"setUpModule\", \"setup_module\")\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/python.py\", line 284, in obj\n",
            "    self._obj = obj = self._getobj()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/python.py\", line 546, in _getobj\n",
            "    return importtestmodule(self.path, self.config)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/python.py\", line 493, in importtestmodule\n",
            "    mod = import_path(\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/pathlib.py\", line 587, in import_path\n",
            "    importlib.import_module(module_name)\n",
            "  File \"/usr/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/_pytest/assertion/rewrite.py\", line 185, in exec_module\n",
            "    exec(co, module.__dict__)\n",
            "  File \"/content/ECE491_Assignment2/cs336-data/tests/test_deduplication.py\", line 6, in <module>\n",
            "    from .adapters import run_exact_line_deduplication, run_minhash_deduplication\n",
            "  File \"/content/ECE491_Assignment2/cs336-data/tests/adapters.py\", line 7, in <module>\n",
            "    from cs336_data.quality import gopher\n",
            "  File \"/content/ECE491_Assignment2/cs336-data/cs336_data/quality.py\", line 1, in <module>\n",
            "    import torch\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/__init__.py\", line 1477, in <module>\n",
            "    from .functional import *  # noqa: F403\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/functional.py\", line 9, in <module>\n",
            "    import torch.nn.functional as F\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/nn/__init__.py\", line 1, in <module>\n",
            "    from .modules import *  # noqa: F403\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/nn/modules/__init__.py\", line 35, in <module>\n",
            "    from .transformer import TransformerEncoder, TransformerDecoder, \\\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py\", line 20, in <module>\n",
            "    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),\n",
            "Fetching 4 files: 100%|██████████| 4/4 [00:06<00:00,  1.57s/it]\n",
            "\u001b[31m\u001b[1m________________________ ERROR collecting cs336-data/tests/test_extract.py _________________________\u001b[0m\n",
            "\u001b[31mImportError while importing test module '/content/ECE491_Assignment2/cs336-data/tests/test_extract.py'.\n",
            "Hint: make sure your test modules/packages have valid Python names.\n",
            "Traceback:\n",
            "/usr/lib/python3.11/importlib/__init__.py:126: in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "cs336-data/tests/test_extract.py:4: in <module>\n",
            "    from .adapters import run_extract_text_from_html_bytes\n",
            "cs336-data/tests/adapters.py:10: in <module>\n",
            "    from cs336_data.minhash_deduplication import fuzzy_deduplication\n",
            "cs336-data/cs336_data/minhash_deduplication.py:2: in <module>\n",
            "    import mmh3\n",
            "E   ModuleNotFoundError: No module named 'mmh3'\u001b[0m\n",
            "\u001b[31m\u001b[1m_________________________ ERROR collecting cs336-data/tests/test_langid.py _________________________\u001b[0m\n",
            "\u001b[31mImportError while importing test module '/content/ECE491_Assignment2/cs336-data/tests/test_langid.py'.\n",
            "Hint: make sure your test modules/packages have valid Python names.\n",
            "Traceback:\n",
            "/usr/lib/python3.11/importlib/__init__.py:126: in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "cs336-data/tests/test_langid.py:4: in <module>\n",
            "    from .adapters import run_identify_language\n",
            "cs336-data/tests/adapters.py:10: in <module>\n",
            "    from cs336_data.minhash_deduplication import fuzzy_deduplication\n",
            "cs336-data/cs336_data/minhash_deduplication.py:2: in <module>\n",
            "    import mmh3\n",
            "E   ModuleNotFoundError: No module named 'mmh3'\u001b[0m\n",
            "\u001b[31m\u001b[1m__________________________ ERROR collecting cs336-data/tests/test_pii.py ___________________________\u001b[0m\n",
            "\u001b[31mImportError while importing test module '/content/ECE491_Assignment2/cs336-data/tests/test_pii.py'.\n",
            "Hint: make sure your test modules/packages have valid Python names.\n",
            "Traceback:\n",
            "/usr/lib/python3.11/importlib/__init__.py:126: in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "cs336-data/tests/test_pii.py:4: in <module>\n",
            "    from .adapters import run_mask_emails, run_mask_ips, run_mask_phone_numbers\n",
            "cs336-data/tests/adapters.py:10: in <module>\n",
            "    from cs336_data.minhash_deduplication import fuzzy_deduplication\n",
            "cs336-data/cs336_data/minhash_deduplication.py:2: in <module>\n",
            "    import mmh3\n",
            "E   ModuleNotFoundError: No module named 'mmh3'\u001b[0m\n",
            "\u001b[31m\u001b[1m________________________ ERROR collecting cs336-data/tests/test_quality.py _________________________\u001b[0m\n",
            "\u001b[31mImportError while importing test module '/content/ECE491_Assignment2/cs336-data/tests/test_quality.py'.\n",
            "Hint: make sure your test modules/packages have valid Python names.\n",
            "Traceback:\n",
            "/usr/lib/python3.11/importlib/__init__.py:126: in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "cs336-data/tests/test_quality.py:4: in <module>\n",
            "    from .adapters import run_classify_quality, run_gopher_quality_filter\n",
            "cs336-data/tests/adapters.py:10: in <module>\n",
            "    from cs336_data.minhash_deduplication import fuzzy_deduplication\n",
            "cs336-data/cs336_data/minhash_deduplication.py:2: in <module>\n",
            "    import mmh3\n",
            "E   ModuleNotFoundError: No module named 'mmh3'\u001b[0m\n",
            "\u001b[31m\u001b[1m________________________ ERROR collecting cs336-data/tests/test_toxicity.py ________________________\u001b[0m\n",
            "\u001b[31mImportError while importing test module '/content/ECE491_Assignment2/cs336-data/tests/test_toxicity.py'.\n",
            "Hint: make sure your test modules/packages have valid Python names.\n",
            "Traceback:\n",
            "/usr/lib/python3.11/importlib/__init__.py:126: in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "cs336-data/tests/test_toxicity.py:4: in <module>\n",
            "    from .adapters import run_classify_nsfw, run_classify_toxic_speech\n",
            "cs336-data/tests/adapters.py:10: in <module>\n",
            "    from cs336_data.minhash_deduplication import fuzzy_deduplication\n",
            "cs336-data/cs336_data/minhash_deduplication.py:2: in <module>\n",
            "    import mmh3\n",
            "E   ModuleNotFoundError: No module named 'mmh3'\u001b[0m\n",
            "\u001b[33m========================================= warnings summary =========================================\u001b[0m\n",
            "../../usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:20\n",
            "  /usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)\n",
            "    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),\n",
            "\n",
            "-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n",
            "\u001b[36m\u001b[1m===================================== short test summary info ======================================\u001b[0m\n",
            "\u001b[31mERROR\u001b[0m cs336-data/tests/test_deduplication.py\n",
            "\u001b[31mERROR\u001b[0m cs336-data/tests/test_extract.py\n",
            "\u001b[31mERROR\u001b[0m cs336-data/tests/test_langid.py\n",
            "\u001b[31mERROR\u001b[0m cs336-data/tests/test_pii.py\n",
            "\u001b[31mERROR\u001b[0m cs336-data/tests/test_quality.py\n",
            "\u001b[31mERROR\u001b[0m cs336-data/tests/test_toxicity.py\n",
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
            "\u001b[31m================================== \u001b[33m1 warning\u001b[0m, \u001b[31m\u001b[1m6 errors\u001b[0m\u001b[31m in 36.65s\u001b[0m\u001b[31m ===================================\u001b[0m\n"
          ]
        }
      ]
    }
  ],
  "metadata": {
    "language_info": {
      "name": "python"
    },
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}